twelvefactor:
  weather:
    api:
      url: http://api.openweathermap.org/data/2.5/weather?q=
      token: "2a5145f9f367e7a725bb8b6f3ea92ff0"

spring:
  application:
    name: "Spring Boot Microservice API - 12 Factor"
    
  profiles:
    active:
    - production
    
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: none
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
  security:
    user:
      name: comunidade
      password: institucional
    
server:
  address: 0.0.0.0
  port: 9000

security:
  oauth2:
    client:
      client-id: twelve-factor-client
      client-secret: ghd8y2tt7-u7d28t672td762-987968tyghubj
      scope: read,write
      auto-approve-scopes: '.*'
  
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
  path: /var/log
  file: twelve-factor-api.log
  
management:
  health:
    db:
      enabled: true